baseURL = "http://www.cbmministry.org/events/gospel/2022/2022-03-26/hugo/"

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

defaultContentLanguage = "en"

# The name of this wonderful theme ;-).
theme = "hugo-scroll"

# The "title" of your website
title = "Home: The eternal God is a dwelling place, and underneath are the everlasting arms ..."

[params]
    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "© Christian Believers Meeting"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "Gospel meeting at CBM 2022-03-26"

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "images/favicon.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and
    # https://gohugo.io/templates/internal#open-graph.
    images = ["img/home_image.jpg"]

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "Home: The eternal God is a dwelling place, and underneath are the everlasting arms ..."

    # This theme will, by default, inject a design-by-line at the bottom of the page.
    # You can turn it off, but we would really appreciate if you don’t :-)
    # hidedesignbyline = true

    [params.meta]
        keywords = "gospel, Christian, Jesus, Christ, salvation, hope, faith, love, save, meaning, purpose, direction, decision,joy"
